name: Publish Plugin
on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Fetch latest submodule updates
        run: git submodule update --remote
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: true
      - name: Setup publish token
        env:
          JETBRAINS_TOKEN: ${{ secrets.JETBRAINS_TOKEN }}
        shell: bash
        run: |
          mkdir -p ~/.gradle/
          echo "GRADLE_USER_HOME=$HOME/.gradle" >> "$GITHUB_ENV"
          echo "mcdev.deploy.token=${JETBRAINS_TOKEN}" > ~/.gradle/gradle.properties
      - name: Publish plugin
        run: ./gradlew clean :publishPlugin --stacktrace
      - name: Get tag name
        id: get_tag
        shell: bash
        # Tag name is reversed from release name due to how IntelliJ parses plugin version numbers
        run: |
          tag_name="$(echo $GITHUB_REF | cut -d / -f 3)"
          echo ::set-output name=tag::$tag_name
          version_array=(${tag_name//-/ })
          echo ::set-output name=release::${version_array[1]}-${version_array[0]}
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          name: 'Release ${{ steps.get_tag.outputs.release }}'
          body: '## [View all plugin releases here.](https://plugins.jetbrains.com/plugin/8327-minecraft-development/versions/stable/)'
          prerelease: false
          draft: false
          files: build/distributions/*.zip
